name: Convert Pack

on:
  push:
    branches: [ main, master ]

jobs:
  packsquash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip Pack
        run: |
          unzip -q "pack.zip" -d temp_unzip
          MCMETA_DIR=$(find temp_unzip -name "pack.mcmeta" -exec dirname {} \;)
          mkdir -p extracted_pack
          cp -r "$MCMETA_DIR"/* extracted_pack/

      - name: Run PackSquash
        uses: PackSquash/packsquash-action@v1
        with:
          options_file: packsquash.toml

      - name: Upload converted pack
        uses: actions/upload-artifact@v4
        with:
          name: converted-mcpack
          path: build/pack.mcpack
